#### General settings, for localhost
#spring:
#  cache:
#    redis:
#      time-to-live: 10S
#  redis:
#    host: localhost
#    port: 6379

#### Settings for Kubernetes (MasterSlaveReplica)
redis:
  master:
    host: redis-0.redis.redis.svc.cluster.local
    port: 6379
  slaves:
    - host: redis-1.redis.redis.svc.cluster.local
      port: 6379
    - host: redis-2.redis.redis.svc.cluster.local
      port: 6379

#### Settings for Kubernetes (test)
#spring:
#  redis:
#     sentinel:
#       master: redis-0.redis.redis.svc.cluster.local:6379
#       nodes:
#         - redis-1.redis.redis.svc.cluster.local:6379
#         - redis-2.redis.redis.svc.cluster.local:6379